# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "agent.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0b\x61gent.proto\x12\x0eqasimodo.agent"\xaf\x01\n\tAgentTask\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x0e\n\x06run_id\x18\x03 \x01(\t\x12\x13\n\x0btestbook_id\x18\x04 \x01(\t\x12\x16\n\x0e\x65nvironment_id\x18\x05 \x01(\t\x12\x14\n\x0cinstructions\x18\x06 \x01(\t\x12\x15\n\rcore_base_url\x18\x07 \x01(\t\x12\x12\n\ncore_token\x18\x08 \x01(\t"\xdf\x01\n\x0b\x41gentResult\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x0e\n\x06run_id\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\r\n\x05\x65rror\x18\x06 \x01(\t\x12\x12\n\nstarted_at\x18\x07 \x01(\t\x12\x13\n\x0b\x66inished_at\x18\x08 \x01(\t\x12\x14\n\x0chistory_json\x18\t \x01(\t\x12\x13\n\x0btestbook_id\x18\n \x01(\t\x12\x16\n\x0e\x65nvironment_id\x18\x0b \x01(\t"\x80\x01\n\x0e\x41gentHeartbeat\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x12\n\nproject_id\x18\x05 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x06 \x03(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "agent_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_AGENTTASK"]._serialized_start = 32
    _globals["_AGENTTASK"]._serialized_end = 207
    _globals["_AGENTRESULT"]._serialized_start = 210
    _globals["_AGENTRESULT"]._serialized_end = 433
    _globals["_AGENTHEARTBEAT"]._serialized_start = 436
    _globals["_AGENTHEARTBEAT"]._serialized_end = 564
# @@protoc_insertion_point(module_scope)
