name: Nix Flake Check
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  check:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
          - system: aarch64-linux
            runner: ubuntu-24.04-arm
          - system: x86_64-darwin
            runner: macos-15-intel
          - system: aarch64-darwin
            runner: macos-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: qasimodo
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Run nix flake check
        run: nix flake check -L --show-trace --system ${{ matrix.system }}
      - name: Build package
        run: nix build .#packages.${{ matrix.system }}.qasimodo-agent -L --show-trace
      - name: Log in to GitHub Container Registry
        if: matrix.system == 'x86_64-linux'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        if: matrix.system == 'x86_64-linux'
        run: |
          # TODO: Add version-specific tags (e.g., sha-<commit>, v<version>) in addition to latest
          nix build .#dockerImage -L --show-trace
          IMAGE_TAG="ghcr.io/${{ github.repository_owner }}/qasimodo-agent:latest"
          ./result | docker load
          LOADED_IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" | head -n 1)
          docker tag $LOADED_IMAGE $IMAGE_TAG
          docker push $IMAGE_TAG
